grpc:
  port: 6565
  enable-reflection: false
  enabled: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.147.3.140:5432/postgres
    username: postgres
    password: postgres
